api/urls.py
from django.urls import path
from . import api

app_name = 'api'

urlpatterns = [
    path('users/', api.UserList.as_view(), name='user_list_api'),
    path('users/<str:user__username>/', api.UserProfileInformation.as_view(), name='profile_api'),
    path('user/', api.CreateProfile.as_view(), name='create_profile_api'),
    path('posts/<str:user__username>/', api.PostList.as_view(), name='posts_api')
]

chat/urls.py
from django.urls import path, include
from chat.views import ChatView, ChatList

app_name = 'chat'

urlpatterns = [
    path('chat_list', ChatList.as_view(), name='chat_list'),
    path('chat_room/<str:username>/', ChatView.as_view(), name='chat_room')
]

friend/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'friend'

urlpatterns = [

    # friend request page with list of received and sent friend requests
    path('friend_request_list/', login_required(login_url='/login')(views.friend_request_list),
         name='friend_request_list'),

    # friend list page of a given user
    path('friend_list/<str:username>', login_required(login_url='/login')(views.friend_list), name='friend_list'),

    # ajax endpoint to send a post request
    path('send_friend_request/', login_required(login_url='/login')(views.send_friend_request),
         name='send_friend_request'),

    # ajax endpoint to accept a friend request
    path('accept_friend_request/', login_required(login_url='/login')(views.accept_friend_request),
         name='accept_friend_request'),

    # ajax endpoint to cancel a friend request
    path('cancel_friend_request/', login_required(login_url='/login')(views.cancel_friend_request),
         name='cancel_friend_request'),

    # ajax endpoint to decline a friend request
    path('decline_friend_request/', login_required(login_url='/login')(views.decline_friend_request),
         name='decline_friend_request'),
]

socialnetworkproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('socialnetwork.urls')),
    path('friend/', include('friend.urls', namespace='friend')),
    path('chat/', include('chat.urls', namespace='chat')),
    path('api/', include('api.urls', namespace='api')),
    path('admin/', admin.site.urls)
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chat/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.


class Chat(models.Model):
    """
    Chat model that creates a room between two users
    """
    user1 = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user1')
    user2 = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user2')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class ChatMessage(models.Model):
    """
    Chat message model that stores the chat messages between two users
    """
    chat = models.ForeignKey(Chat, on_delete=models.CASCADE)
    sender = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField(blank=False, null=False)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.content

chat/views.py
from django.shortcuts import render
from django.views import View
from django.db.models import Q
from django.contrib.auth import get_user_model
from chat.models import Chat


# Create your views here.

class ChatList(View):

    def get(self, request, **kwargs):

        chat_list = Chat.objects.get_queryset().filter(Q(user1=self.request.user) | Q(user2=self.request.user))
        chat_user_list = []

        for chat in chat_list:
            if chat.user1 != self.request.user:
                chat_user_list.append(chat.user1)
            elif chat.user2 != self.request.user:
                chat_user_list.append(chat.user2)

        context = {
            "chat_list": zip(chat_list, chat_user_list)
        }

        return render(request, 'chat/chat_list.html', context)


class ChatView(View):
    def get_object(self):
        self.user_one = self.request.user
        self.user_two = get_user_model().objects.get(username=self.kwargs.get("username"))

        chat_room = Chat.objects.get_queryset().filter(
            (Q(user1=self.user_one) and Q(user2=self.user_two)) | (
                    Q(user1=self.user_two) and Q(user2=self.user_one)))

        if chat_room.exists():
            return chat_room.first()
        else:
            chat_room = Chat.objects.create(user1=self.request.user, user2=self.user_two)

        return chat_room

    def get(self, request, **kwargs):
        context = {
            "user": self.request.user,
            "chat": self.get_object(),
            "friend": self.user_two,
            "messages": self.get_object().chatmessage_set.all()
        }

        return render(request, 'chat/chat.html', context=context)

chat/templates/chat/chat.html
{% include "base.html" %}
{% load tz %}

{% block content %}
    <div class="container my-3">
        <div class="row">
            <div class="col-md-10 mx-auto my-2">
                <h2>Chat between: {{ user.username }} and {{ friend.username }}</h2>
            </div>
            <div class="col-md-10 mx-auto card shadow-sm" style="height: 80vh;">

                <div id="message-container" class="overflow-auto d-flex flex-md-column" style="height: 80%;">
                    <div id="message-list">
                        {% for message in messages %}
                            {% if message.sender.username == user.username %}
                                <div class="text-start m-2 d-flex flex-column justify-content-start align-items-end">
                                    <div>
                                        <span class="fw-bold">{{ message.sender.username }}</span>
                                        <span class="chat-message-date">{{ message.timestamp|localtime }}</span>
                                    </div>
                                    <div class="chat-bubble-right">
                                        <span>{{ message.content }}</span>
                                    </div>
                                </div>
                            {% else %}
                                <div class="text-start m-2 flex-column d-flex justify-content-start align-items-start">
                                    <div>
                                        <span class="fw-bold">{{ message.sender.username }}</span>
                                        <span class="chat-message-date">{{ message.timestamp|localtime }}</span>
                                    </div>
                                    <div class="chat-bubble-left">
                                        <span>{{ message.content }}</span>
                                    </div>
                                </div>
                            {% endif %}

                        {% endfor %}
                    </div>
                </div>
                <textarea class="form-control" name="message" id="chat-message-input" rows="3" required></textarea>
                <input type="submit" value="Send" id="chat-message-submit" class="btn btn-primary my-3">
            </div>
        </div>
    </div>
{% endblock content %}

<script>

    // scroll to bottom of chat
    const element = document.getElementById("message-container");
    element.scrollTop = element.scrollHeight;

    // web socket connection
    const chatSocket = new WebSocket(
        'ws://'
        + window.location.host
        + '/ws'
        + window.location.pathname
    );

    chatSocket.onopen = function (event) {
        console.log('Connection is open')
    }

    chatSocket.onmessage = function (event) {
        console.log('Message received', event)

        $("#message-list").append(
            "<div class='text-start m-2 flex-column d-flex justify-content-start align-items-end'>" +
            "<div>" +
            "<span class='fw-bold'>" + JSON.parse(event.data).username +
            "</span>" +
            "<span class='chat-message-date'> " + new Date().toDateString() +
            "</span>" +
            "</div>" +
            "<div class='chat-bubble-right'>" + "<span>" + JSON.parse(event.data).text + "</span>" + "</div>" +
            "</div>"
        );

        element.scrollTop = element.scrollHeight;

    }

    chatSocket.onclose = function (event) {
        console.log('Connection closed', event)
    }

    chatSocket.onerror = function (event) {
        console.log('Something went wrong', event)
    }

    document.querySelector('#chat-message-submit').onclick = function (e) {
        const messageInputDom = document.querySelector('#chat-message-input');
        const message = messageInputDom.value;
        chatSocket.send(JSON.stringify({ "message": message }));
        messageInputDom.value = '';
        element.scrollTop = element.scrollHeight;
    }


</script>

chat/templates/chat/chat_list.html
{% include "base.html" %} {% block content %}

<div class="container">
  <div class="row">
    <div class="col-md-8 col-sm-12 mx-auto">
      {% if chat_list %}
      <div><h3 class="mt-5">Continue a conversation with your friend!</h3></div>
      <div class="row mt-5">
        {% for chat_obj, chat_user in chat_list %}
        <div class="col-12">
          <div class="card p-3 shadow-sm">
            <div class="d-flex align-items-center justify-content-between">
              <div class="d-flex align-items-center">
                {% if chat_user.userprofile.avatar %}
                <img src="{{ chat_user.userprofile.avatar.url }}" class="rounded-circle" width="75" height="75" />
                {% endif %}
                <div class="mx-3">
                  <p class="card-title font-weight-light">
                    <em>@{{ chat_user }}</em>
                  </p>
                  <h5>{{ chat_user.first_name }} {{ chat_user.last_name }}</h5>
                  <span>Last chat at {{ chat_obj.updated_at }}</span>
                </div>
              </div>
              <div>
                <a href="{% url 'profile' chat_user.username %}" class="btn btn-primary">View Profile</a>
                <a href="{% url 'chat:chat_room' chat_user %}" class="btn btn-success my-2">Chat</a>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
      {% else %}
      <h3 class="mt-5">No User found with the given name. Please try again...</h3>
      {% endif %}
    </div>
    <div class="col-md-8 col-sm-12 mx-auto mt-5">
      <div class="my-3">
        <span>Or start a new conversation here </span>
        <a class="btn btn-primary" href="{% url 'friend:friend_list' user.username %}"> Go to friends list </a>
      </div>
    </div>
  </div>
</div>

{% endblock %}