api/urls.py
from django.urls import path
from . import api

app_name = 'api'

urlpatterns = [
    path('users/', api.UserList.as_view(), name='user_list_api'),
    path('users/<str:user__username>/', api.UserProfileInformation.as_view(), name='profile_api'),
    path('user/', api.CreateProfile.as_view(), name='create_profile_api'),
    path('posts/<str:user__username>/', api.PostList.as_view(), name='posts_api')
]

chat/urls.py
from django.urls import path, include
from chat.views import ChatView, ChatList

app_name = 'chat'

urlpatterns = [
    path('chat_list', ChatList.as_view(), name='chat_list'),
    path('chat_room/<str:username>/', ChatView.as_view(), name='chat_room')
]

socialnetworkproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('socialnetwork.urls')),
    path('friend/', include('friend.urls', namespace='friend')),
    path('chat/', include('chat.urls', namespace='chat')),
    path('api/', include('api.urls', namespace='api')),
    path('admin/', admin.site.urls)
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/snippets/header.html
{% load static %}
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <link rel="stylesheet" href = "{% static 'css/styles.css' %}">

    <title>ConnectU - Social Network</title>
</head>

templates/snippets/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'home' %}">ConnectU</a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarTogglerDemo02"
      aria-controls="navbarTogglerDemo02"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item d-flex align-items-center">
          <a class="nav-link" href="{% url 'chat:chat_list' %}">Inbox</a>
        </li>
      </ul>
      <ul class="navbar-nav mb-2 mb-lg-0">
        <li class="nav-item d-flex align-items-center">
          <form class="d-flex" method="get" action="{% url 'user-search' %}">
            <input
              class="form-control me-2"
              type="search"
              placeholder="Search"
              aria-label="Search"
              name="query"
              value="{{request.GET.query}}"
            />
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
        </li>
        <li class="nav-item">
          <a class="nav-link d-flex align-items-center" href="{% url 'profile' request.user.username %}">
            <img src="{{ request.user.userprofile.avatar.url }}" class="rounded-circle" height="35px" width="35" />
            <strong class="mx-2 my-0"> {{ request.user.username }} </strong>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link d-flex align-items-center mt-1" href="{% url 'logout' %}"> Logout </a>
        </li>
      </ul>
    </div>
  </div>
</nav>