api/urls.py
from django.urls import path
from . import api

app_name = 'api'

urlpatterns = [
    path('users/', api.UserList.as_view(), name='user_list_api'),
    path('users/<str:user__username>/', api.UserProfileInformation.as_view(), name='profile_api'),
    path('user/', api.CreateProfile.as_view(), name='create_profile_api'),
    path('posts/<str:user__username>/', api.PostList.as_view(), name='posts_api')
]

friend/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'friend'

urlpatterns = [

    # friend request page with list of received and sent friend requests
    path('friend_request_list/', login_required(login_url='/login')(views.friend_request_list),
         name='friend_request_list'),

    # friend list page of a given user
    path('friend_list/<str:username>', login_required(login_url='/login')(views.friend_list), name='friend_list'),

    # ajax endpoint to send a post request
    path('send_friend_request/', login_required(login_url='/login')(views.send_friend_request),
         name='send_friend_request'),

    # ajax endpoint to accept a friend request
    path('accept_friend_request/', login_required(login_url='/login')(views.accept_friend_request),
         name='accept_friend_request'),

    # ajax endpoint to cancel a friend request
    path('cancel_friend_request/', login_required(login_url='/login')(views.cancel_friend_request),
         name='cancel_friend_request'),

    # ajax endpoint to decline a friend request
    path('decline_friend_request/', login_required(login_url='/login')(views.decline_friend_request),
         name='decline_friend_request'),
]

socialnetwork/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

urlpatterns = [

    # signup route that displays signup page
    path('signup/', views.user_signup, name='signup'),

    # login route that displays login page
    path('login/', views.user_login, name='login'),

    # logout route to log out user from the application
    path('logout/', views.user_logout, name='logout'),

    # ------ Login is required to query the below endpoints. ------

    # Home page that shows user list of posts by them and their friends.
    path('', login_required(login_url='/login')(views.Home.as_view()), name='home'),

    # Profile page with the username as the query parameter to display their posts and profile information.
    path('profile/<str:username>', login_required(login_url='/login')(views.Profile.as_view()), name='profile'),

    # Edit Profile page to edit their profile information by the logged in user.
    path('profile/edit/', login_required(login_url='/login')(views.EditProfile.as_view()), name='profile-edit'),

    # User search page to display all the users based on the keywords entered by the user.
    path('search/', login_required(login_url='/login')(views.UserSearch.as_view()), name='user-search'),

    # AJAX endpoint to upvote post by the logged in user.
    path('upvote_post/', login_required(login_url='/login')(views.upvote_post),
         name='upvote_post'),
]

socialnetworkproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('socialnetwork.urls')),
    path('friend/', include('friend.urls', namespace='friend')),
    path('chat/', include('chat.urls', namespace='chat')),
    path('api/', include('api.urls', namespace='api')),
    path('admin/', admin.site.urls)
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

socialnetwork/forms.py
from django import forms
from django.forms import ModelForm
from .models import *
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

# User sign up form extending UserCreationForm
class UserSignupForm(UserCreationForm):
    first_name = forms.CharField(label="First Name", max_length=50,
                                 widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(label="Last Name", max_length=50,
                                widget=forms.TextInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(label="Password",
                                widget=forms.PasswordInput(attrs={'class': 'form-control', 'autocomplete': 'off'}))
    password2 = forms.CharField(label="Confirm Password",
                                widget=forms.PasswordInput(
                                    attrs={'class': 'form-control', 'autocomplete': 'off'}))
    email = forms.CharField(label="Email", max_length=120, widget=forms.TextInput(attrs={'class': 'form-control'}))
    username = forms.CharField(label="Username", max_length=30,
                               widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password1', 'password2')

    # removing colon after labels
    def __init__(self, *args, **kwargs):
        kwargs.setdefault('label_suffix', '')
        super(UserSignupForm, self).__init__(*args, **kwargs)


# User Profile form
class UserProfileForm(forms.ModelForm):
    avatar = forms.ImageField(required=False, error_messages={'invalid': "Image files only."},
                                       widget=forms.FileInput, label="Profile Picture")
    status = forms.CharField(required=False, error_messages={'invalid': "This field is required."},
                             widget=forms.TextInput(attrs={'class': 'form-control'}), max_length=200)
    profile_visibility = forms.BooleanField(required=False,
                                            widget=forms.CheckboxInput(
                                                attrs={'class': 'form-check-input'}),
                                            label="Make your profile visible to users you are not friend with?")

    class Meta:
        model = UserProfile
        fields = ('avatar', 'status', 'profile_visibility')

    def __init__(self, *args, **kwargs):
        kwargs.setdefault('label_suffix', '')
        super(UserProfileForm, self).__init__(*args, **kwargs)


# User form
class UserForm(forms.ModelForm):
    first_name = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.CharField(label="Email", max_length=120, widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')


# Post form
class PostForm(forms.ModelForm):
    text = forms.CharField(
        widget=forms.Textarea(
            attrs={'class': 'form-control', 'placeholder': 'Have something to share? Tell us here!', 'rows': 5}),
        label="Tell us something!")
    image = forms.ImageField(required=False, error_messages={'invalid': "Image files only"}, widget=forms.FileInput,
                             label="Add an image (Optional)")

    class Meta:
        model = UserPost
        fields = ['text', 'image']

socialnetwork/views.py
from django.shortcuts import redirect, render
from django.views import View
from .forms import *
from .models import *
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from friend.models import FriendRequest
from django.db.models.query_utils import Q
from django.http import JsonResponse


# Create your views here.

@login_required
def user_logout(request):
    """
    Log out user

    :param request:
    :return:
    """

    logout(request)
    return redirect('/login')


def user_login(request):
    """
    Log in user

    :param request:
    :return:
    """

    # redirecting to home page if user is already authenticated
    if request.user.is_authenticated:
        return redirect('/')

    # checking for the request type
    if request.method == 'POST':

        username = request.POST['username']
        password = request.POST['password']

        # authenticating user
        user = authenticate(username=username, password=password)

        # checking if user exists
        if user:
            # check if their account is active
            if user.is_active:
                # login user
                login(request, user)
                messages.success(request, 'Logged in.')

                return redirect('/')
            else:
                messages.error(request, 'Your account is disabled.')
        else:
            messages.error(request, 'Incorrect credentials entered.')

    return render(request, 'socialnetwork/login.html')


def user_signup(request):
    """
    Register a new user

    :param request:
    :return:
    """

    # redirecting to home page if user is already authenticated
    if request.user.is_authenticated:
        return redirect('/')

    if request.method == 'POST':

        # create user signup and profile form instance with the request values
        user_form = UserSignupForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)

        # checking if the forms are valid
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            profile.save()
            messages.success(request, 'User account created successfully.')

            return redirect('/login')

        else:
            print(user_form.errors, profile_form.errors)
    else:

        # if request is not post, then show the user with a blank forms to fill it
        user_form = UserSignupForm()
        profile_form = UserProfileForm()

    # pass the forms as a context to the template
    context = {
        'user_form': user_form,
        'profile_form': profile_form
    }

    return render(request, 'socialnetwork/signup.html', context)


class Home(View):
    def get(self, request, *args, **kwargs):
        """
        Returns the list of post by user and their friends
        :param request:
        :param args:
        :param kwargs:
        :return:
        """

        # finding the logged in user's profile
        profile = UserProfile.objects.filter(user=request.user).first()

        # checkinf if profile exists
        if profile is not None:

            # finding all friends of logged in user
            user_friends = profile.user.userprofile.friends.all()

            # finding all user posts created by the author and their friends
            feed_posts = UserPost.objects.filter(Q(author__in=user_friends) | Q(author=request.user)).order_by(
                '-created_at')

            # empty Post form
            post_form = PostForm()

            # passing the post list and empty form as a context to the template
            context = {
                'post_list': feed_posts,
                'post_form': post_form
            }

            return render(request, 'socialnetwork/home.html', context)

        else:
            messages.error(request, 'No profile found with the given username.')
            logout(request)
            return redirect('/login')

    def post(self, request, *args, **kwargs):
        """
        Show the post form for logged in user to create and share post
        :param request:
        :param args:
        :param kwargs:
        :return:
        """

        # creating an instance of post form with request values
        post_form = PostForm(request.POST, request.FILES)

        # finding the logged in user's profile
        profile = UserProfile.objects.filter(user=request.user).first()

        # checking if the form is valid and user is authenticated
        if request.user.is_authenticated & post_form.is_valid():
            post = post_form.save(commit=False)
            post.author = request.user
            post.save()

            # finding all logged in user's friends
            user_friends = profile.user.userprofile.friends.all()

            # finding all user posts created by the author and their friends
            feed_posts = UserPost.objects.filter(Q(author__in=user_friends) | Q(author=request.user)).order_by(
                '-created_at')

            messages.success(request, 'New post created successfully.')

            # empty Post form
            new_post_form = PostForm()

            # passing the post list and empty form as a context to the template
            context = {
                'post_list': feed_posts,
                'post_form': new_post_form
            }

            return render(request, 'socialnetwork/home.html', context)


class Profile(View):

    def get(self, request, username, *args, **kwargs):

        """
        finds the user profile by the username

        :param request:
        :param username:
        :param args:
        :param kwargs:
        :return:
        """

        # search for the user profile by username
        profile = UserProfile.objects.get(user__username=username)
        # find profile posts created by the user in the descending order
        profile_posts = UserPost.objects.filter(author=profile.user).order_by('-created_at')
        # find the list of friends associated with the profile
        profile_friends = profile.friends.all()

        # checking if the request is authenticated and the logged in user is the same as the profile user
        if request.user.is_authenticated and request.user == profile.user:
            # finding all the friend requests received and sent by the user
            received_requests = FriendRequest.objects.filter(receiver=request.user, is_active=True)
            sent_requests = FriendRequest.objects.filter(sender=request.user, is_active=True)

            return render(request, 'socialnetwork/profile.html', {
                "user": request.user,
                "profile": profile,
                "post_list": profile_posts,
                "friends": profile_friends,
                "logged_in_user": True,
                "is_friend": False,
                "friend_requests": len(sent_requests) + len(received_requests),
                "show_profile": True
            })

        # if the authenticated user is not same as the profile user
        if request.user.is_authenticated and request.user != profile.user:

            # check if the authenticated user is already friend with a profile user
            check_if_friend = True if profile_friends.filter(username=request.user.username) else False

            if check_if_friend:
                return render(request, 'socialnetwork/profile.html', {
                    "user": request.user,
                    "profile": profile,
                    "post_list": profile_posts,
                    "friends": profile_friends,
                    "logged_in_user": False,
                    "is_friend": check_if_friend,
                    "show_profile": True
                })

            else:
                if validate_request(profile.user, request.user):
                    friend_request_by_user = validate_request(profile.user, request.user)

                    return render(request, 'socialnetwork/profile.html', {
                        "user": request.user,
                        "profile": profile,
                        "post_list": profile_posts,
                        "friends": profile_friends,
                        "logged_in_user": False,
                        "is_friend": check_if_friend,
                        "request_by_user": friend_request_by_user.id,
                        "sent_request": "received_request",
                        "show_profile": profile.profile_visibility
                    })

                elif validate_request(request.user, profile.user):
                    friend_request_receiver = validate_request(request.user,
                                                               profile.user)

                    return render(request, 'socialnetwork/profile.html', {
                        "user": request.user,
                        "profile": profile,
                        "post_list": profile_posts,
                        "friends": profile_friends,
                        "logged_in_user": False,
                        "is_friend": check_if_friend,
                        "request_receiver": friend_request_receiver.id,
                        "sent_request": "send_request",
                        "show_profile": profile.profile_visibility
                    })

                else:

                    return render(request, 'socialnetwork/profile.html', {
                        "user": request.user,
                        "profile": profile,
                        "post_list": profile_posts,
                        "friends": profile_friends,
                        "logged_in_user": False,
                        "is_friend": check_if_friend,
                        "sent_request": "no_request",

socialnetwork/templates/socialnetwork/home.html
{% extends "base.html" %}

{% block content %}
    <div class="container my-3">
        <div class="row">
            {% if user.is_authenticated %}
                <div class="col-md-8 col-sm-12 mx-auto">
                    {% if messages %}
                        {% for message in messages %}
                            <div {% if message.tags %}
                                {% if message.tags == "error" %}
                                    class="alert alert-danger"
                                {% endif %}
                                    class="alert alert-{{ message.tags }} alert-dismissible fade show"
                            {% endif %}
                                    role="alert">
                                {{ message }}
                                <button type="button" class="btn-close" data-bs-dismiss="alert"
                                        aria-label="Close"></button>
                            </div>
                        {% endfor %}
                    {% endif %}
                </div>

                <div class="col-md-8 col-sm-12 mx-auto">
                    <form id="post_form" method="post" action=""
                          enctype="multipart/form-data">
                        {% csrf_token %}
                        <div>
                            <label class="form-label" for="text">{{ post_form.text.label_tag }}</label>
                            {{ post_form.text }}
                        </div>
                        <p class="text-danger"><small>{{ post_form.text.errors.0 }}</small></p>

                        <div class="d-flex flex-row align-items-center">
                            <div class="d-flex">
                                <label class="form-label" for="image">{{ post_form.image.label_tag }} &nbsp;</label>
                                {{ post_form.image }}
                            </div>
                            <p class="text-danger"><small>{{ post_form.image.errors.0 }}</small></p>
                        </div>

                        <div class="d-grip gap-2 d-flex justify-content-end">
                            <button type="submit" name="submit" class="btn btn-primary">Share this post</button>
                        </div>

                    </form>
                </div>

                <div class="col-md-8 col-sm-12 mx-auto py-4">
                    <h3>My feed</h3>
                    {% if post_list %}
                        {% for post in post_list %}
                            <div class="card mb-3 my-3 shadow-sm">
                                <div class="card-header d-flex justify-content-between align-items-center">
                                    <div class="author-details d-flex align-items-center">
                                        <img src="{{ post.author.userprofile.avatar.url }}"
                                             class="rounded-circle"
                                             width="50" height="50"/>
                                        <a href="{% url 'profile' post.author.username %}"
                                           class="text-decoration-none text-reset mx-3 my-0 fw-bold"> {{ post.author.username }} </a>
                                    </div>
                                    <div>
                                        <p class="card-text"><small class="text-muted">{{ post.created_at }}</small>
                                        </p>
                                    </div>
                                </div>
                                <div class="card-body">
                                    <p class="card-text">{{ post.text }}</p>
                                    {% if post.image %}
                                        <img src="{{ post.image.url }}" class="rounded mx-auto d-block" alt="..."
                                             style="height: 300px; width:250px;">
                                    {% endif %}

                                    <button class="btn btn-success btn-sm"
                                            onclick='upvoteUserPost("{{ post.id }}")'>
                                        Upvote ({{ post.user_likes.all.count }})
                                    </button>
                                </div>
                            </div>
                        {% endfor %}
                    {% else %}
                        <div class="d-flex justify-content-center mt-5">
                            <h5>Nothing to show here...</h5>
                        </div>
                    {% endif %}
                </div>

            {% else %}
                <p>Welcome, new user. Please log in.</p>
            {% endif %}
        </div>
    </div>

{% endblock %}

socialnetwork/templates/socialnetwork/profile.html
{% include "base.html" %}

{% block content %}

    <div class="container my-5">
        <div class="row">
            <div class="col-md-8 col-sm-12 mx-auto">
                {% if messages %}
                    {% for message in messages %}
                        <div {% if message.tags %}
                            {% if message.tags == "error" %}
                                class="alert alert-danger alert-dismissible fade show"
                            {% endif %}
                                class="alert alert-{{ message.tags }} alert-dismissible fade show"
                        {% endif %}
                                role="alert">
                            {{ message }}
                            <button type="button" class="btn-close" data-bs-dismiss="alert"
                                    aria-label="Close"></button>
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
        </div>

        <div class="row">
            <div class="col-md-8 col-sm-12 mx-auto">
                <div class="card">
                    <div class="card-body shadow-sm">
                        <div class="d-flex justify-content-between">
                            <div class="d-flex">
                                <div>
                                    {% if profile.avatar %}
                                        <img class="rounded" src="{{ profile.avatar.url }}" width="200px"
                                             height="200px"/>
                                    {% endif %}
                                </div>
                                <div class="m-4">
                                    <h5> @{{ profile.user.username }} </h5>

                                    {% if profile.user.first_name %}
                                        <h3>{{ profile.user.first_name }} {{ profile.user.last_name }}</h3>
                                    {% endif %}

                                    {% if profile.status %}
                                        <p class="text-weight-light">{{ profile.status }}</p>
                                    {% endif %}

                                    {% if logged_in_user %}
                                        <a class="btn btn-warning" href="{% url 'profile-edit' %}"> Edit Profile</a>
                                    {% endif %}

                                    {% if is_friend %}
                                        <span class="badge bg-primary disabled">You both are friends.</span>
                                    {% endif %}

                                    <!-- if not own profile and not a friend, then show request status -->
                                    {% if not is_friend and not logged_in_user %}
                                        {% if sent_request == 'no_request' %}
                                            <button class="btn btn-primary"
                                                    onclick='sendFriendRequest("{{ profile.user.username }}")'>
                                                Send Friend Request
                                            </button>
                                        {% endif %}
                                        {% if sent_request == 'received_request' %}
                                            <p>Pending friend request:</p>
                                            <div class="d-flex">
                                                <button class="btn btn-secondary"
                                                        onclick='acceptFriendRequest("{{ request_by_user }}")'>
                                                    Accept
                                                </button>
                                                <button class="btn btn-danger mx-3"
                                                        onclick='declineFriendRequest("{{ request_by_user }}")'>
                                                    Decline
                                                </button>
                                            </div>
                                        {% endif %}
                                        {% if sent_request == "send_request" %}
                                            <div class="d-flex">
                                                <button class="btn btn-danger btn-sm"
                                                        onclick='cancelFriendRequest("{{ request_receiver }}")'>
                                                    Cancel Friend Request
                                                </button>
                                            </div>
                                        {% endif %}
                                    {% endif %}

                                </div>
                            </div>
                            <div class="d-flex flex-row justify-content-center align-items-center">

                                <div class="me-2">
                                    <a class="btn btn-primary"
                                       href="{% url 'friend:friend_list' profile.user.username %}">Friends
                                        ({{ friends|length }})</a>
                                </div>
                                {% if logged_in_user %}
                                    <div>
                                        <a class="btn btn-warning" href="{% url 'friend:friend_request_list' %}">Friend
                                            requests
                                            ({{ friend_requests }})</a>
                                    </div>
                                {% endif %}
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-8 col-sm-12 mx-auto py-4">
            <h4 class="my-3">My Activity</h4>
            {% if show_profile %}
                {% if post_list %}
                    {% for post in post_list %}
                        <div class="card mb-3 my-3 shadow-sm">
                            <div class="card-header d-flex justify-content-between align-items-center">
                                <div class="author-details d-flex align-items-center">
                                    <img src="{{ post.author.userprofile.avatar.url }}"
                                         class="rounded-circle"
                                         width="50" height="50"/>
                                    <a href="{% url 'profile' post.author.username %}"
                                       class="text-decoration-none text-reset mx-3 my-0 fw-bold"> {{ post.author.username }} </a>
                                </div>
                                <div>
                                    <p class="card-text"><small class="text-muted">{{ post.created_at }}</small>
                                    </p>
                                </div>
                            </div>
                            <div class="card-body">
                                <p class="card-text">{{ post.text }}</p>
                                {% if post.image %}
                                    <img src="{{ post.image.url }}" class="rounded mx-auto d-block" alt="..."
                                         style="height: 300px; width:250px;">
                                {% endif %}

                                <button class="btn btn-success btn-sm"
                                        onclick='upvoteUserPost("{{ post.id }}")'>
                                    Upvote ({{ post.user_likes.all.count }})
                                </button>
                            </div>
                        </div>
                    {% endfor %}

                {% else %}
                    <div class="d-flex justify-content-center mt-5">
                        <h5>Nothing to show here...</h5>
                    </div>
                {% endif %}
            {% else %}
                <div class="d-flex justify-content-center mt-5">
                    <h5>This profile is private...</h5>
                </div>
            {% endif %}
        </div>
    </div>

{% endblock %}